### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by zhiruozzy** [goverclock/Playground#1]
尊敬的作者，我有一些问题想要请教您，我给您的这个邮箱goverclock@outlook.com发了邮件，您可以抽空看一下吗，十分感谢

**Comment by goverclock** [comment]
你好!其实昨天就看见了你的邮件并尝试回复,无奈于你的邮箱地址似乎是有问题的,我多次尝试都被提示未送达:
![img](https://pic.sl.al/gdrive/pic/2023-05-31/6476aef4cba6c.png)
如果有什么问题就直接在相应的代码的地方开issue吧,或者换一个邮箱发过来: )

**Comment by zhiruozzy** [comment]
哇学长您好，能收到您的回复真是太好了。我可以加一下您的QQ吗，邮箱沟通起来不是很方便，我的QQ号是2490932295，麻烦您了~&nbsp;


EVE
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [goverclock/Playground] issue (Issue #1)





 
你好!其实昨天就看见了你的邮件并尝试回复,无奈于你的邮箱地址似乎是有问题的,我多次尝试都被提示未送达:
 
 如果有什么问题就直接在相应的代码的地方开issue吧,或者换一个邮箱发过来: )
